// src/components/button/demo/block.tsx
import { Button, Flex } from '@/components';

const App = () => (
  <Flex vertical gap="small" style={{ width: '100%' }}>
    <Button type="primary" block>
      Primary
    </Button>
    <Button block>Default</Button>
    <Button type="dashed" block>
      Dashed
    </Button>
    <Button disabled block>
      disabled
    </Button>
    <Button type="text" block>
      text
    </Button>
    <Button type="link" block>
      Link
    </Button>
  </Flex>
);

export default App;

// src/client/demos/button/block.vue
<script lang="tsx" setup>
import { Button, Flex } from '@/components';
</script>
<template>
  <Flex vertical gap="small" style="width: 100%">
    <Button type="primary" block> Primary </Button>
    <Button block>Default</Button>
    <Button type="dashed" block> Dashed </Button>
    <Button disabled block> disabled </Button>
    <Button type="text" block> text </Button>
    <Button type="link" block> Link </Button>
  </Flex>
</template>
