// src/components/button/demo/danger.tsx
import { Button, Flex } from '@/components';

const App = () => (
  <Flex wrap gap="small">
    <Button type="primary" danger>
      Primary
    </Button>
    <Button danger>Default</Button>
    <Button type="dashed" danger>
      Dashed
    </Button>
    <Button type="text" danger>
      Text
    </Button>
    <Button type="link" danger>
      Link
    </Button>
  </Flex>
);

export default App;

// src/client/demos/button/danger.vue
<script lang="tsx" setup>
import { Button, Flex } from '@/components';
</script>
<template>
  <Flex wrap gap="small">
    <Button type="primary" danger> Primary </Button>
    <Button danger>Default</Button>
    <Button type="dashed" danger> Dashed </Button>
    <Button type="text" danger> Text </Button>
    <Button type="link" danger> Link </Button>
  </Flex>
</template>
